// TURNOUT CONTROL 
// NEED TO FIX, USE PWM PIN TO NOT BURN SOLENOID
#define PULSE 50 // 50ms
#define I2C_ADDRESS 0x65

// DEFINE SINGLE_COIL_TURNOUT MACRO
#define SINGLE_COIL_TURNOUT(t, p1, p2, desc) \
VIRTUAL_TURNOUT(t, desc) \
DONE \
ONCLOSE(t) \
  SET(p1) DELAY (PULSE) RESET(p1) \
DONE \
ONTHROW(t) \
  SET(p2) DELAY(PULSE) RESET(p2) \
DONE


ROSTER(2586, "NS")
//ROSTER(111, "CSX")

SINGLE_COIL_TURNOUT(100, 23, 22, "Right Turnout")
SINGLE_COIL_TURNOUT(200, 25, 24, "Left Turnout")

/*
// TRAFFIC SIGNAL 
// GREEN: 28, AMBER: 27, RED: 26
SIGNAL(26, 27, 28)

VIRTUAL_SIGNAL(300)
*/

//TEMPORARY: JMRI_SENSOR(831) IS DIGITAL PIN 35 ON EXPANDER ARDUINO
JMRI_SENSOR(831)
JMRI_SENSOR(36)

//TURN ON PIN 2 OF EXPANDER ARDUINO
SEQUENCE(1)
  AUTOSTART
  SET(800)
FOLLOW(1)

/*
ONRED(300)
  RED(26)
DONE

ONAMBER(300)
  AMBER(26)
DONE

ONGREEN(300)
  GREEN(26)
DONE
*/

